apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  labels:
    type: local
spec:
  capacity:
    storage: 256Mi
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/db